.pragma library

var emoji = [
    // Smileys
    {char:"😀",name:"grinning face"},{char:"😃",name:"grinning face with big eyes"},
    {char:"😄",name:"grinning face with smiling eyes"},{char:"😁",name:"beaming face"},
    {char:"😆",name:"grinning squinting face"},{char:"😅",name:"grinning face with sweat"},
    {char:"😂",name:"face with tears of joy"},{char:"🤣",name:"rolling on floor laughing"},
    {char:"😊",name:"smiling face with smiling eyes"},{char:"😇",name:"smiling face with halo"},
    {char:"🙂",name:"slightly smiling face"},{char:"😉",name:"winking face"},
    {char:"😍",name:"smiling face with heart eyes"},{char:"🥰",name:"smiling face with hearts"},
    {char:"😘",name:"face blowing a kiss"},{char:"😋",name:"face savoring food"},
    {char:"😜",name:"winking face with tongue"},{char:"🤪",name:"zany face"},
    {char:"😎",name:"smiling face with sunglasses"},{char:"🥳",name:"partying face"},
    {char:"😏",name:"smirking face"},{char:"😒",name:"unamused face"},
    {char:"😔",name:"pensive face"},{char:"😢",name:"crying face"},
    {char:"😭",name:"loudly crying face"},{char:"😤",name:"face with steam from nose"},
    {char:"😠",name:"angry face"},{char:"🤬",name:"face with symbols on mouth"},
    {char:"😱",name:"face screaming in fear"},{char:"😨",name:"fearful face"},
    {char:"😰",name:"anxious face with sweat"},{char:"😴",name:"sleeping face"},
    {char:"🤔",name:"thinking face"},{char:"🤨",name:"face with raised eyebrow"},
    {char:"😐",name:"neutral face"},{char:"🙄",name:"face with rolling eyes"},
    {char:"😬",name:"grimacing face"},{char:"🤥",name:"lying face"},
    {char:"🤤",name:"drooling face"},{char:"🥺",name:"pleading face"},
    // Hearts & affection
    {char:"❤️",name:"red heart"},{char:"🧡",name:"orange heart"},
    {char:"💛",name:"yellow heart"},{char:"💚",name:"green heart"},
    {char:"💙",name:"blue heart"},{char:"💜",name:"purple heart"},
    {char:"🖤",name:"black heart"},{char:"🤍",name:"white heart"},
    {char:"💔",name:"broken heart"},{char:"💕",name:"two hearts"},
    {char:"💞",name:"revolving hearts"},{char:"💓",name:"beating heart"},
    // Hands & gestures
    {char:"👋",name:"waving hand"},{char:"🤚",name:"raised back of hand"},
    {char:"✋",name:"raised hand"},{char:"🖖",name:"vulcan salute"},
    {char:"👌",name:"ok hand"},{char:"✌️",name:"victory hand"},
    {char:"🤞",name:"crossed fingers"},{char:"🤙",name:"call me hand"},
    {char:"👈",name:"backhand index pointing left"},{char:"👉",name:"backhand index pointing right"},
    {char:"👆",name:"backhand index pointing up"},{char:"👇",name:"backhand index pointing down"},
    {char:"☝️",name:"index pointing up"},{char:"👍",name:"thumbs up"},
    {char:"👎",name:"thumbs down"},{char:"✊",name:"raised fist"},
    {char:"👏",name:"clapping hands"},{char:"🙌",name:"raising hands"},
    {char:"🤲",name:"palms up together"},{char:"🤝",name:"handshake"},
    {char:"🙏",name:"folded hands"},
    // Animals
    {char:"🐶",name:"dog face"},{char:"🐱",name:"cat face"},
    {char:"🐭",name:"mouse face"},{char:"🐹",name:"hamster"},
    {char:"🐰",name:"rabbit face"},{char:"🦊",name:"fox"},
    {char:"🐻",name:"bear"},{char:"🐼",name:"panda"},
    {char:"🐨",name:"koala"},{char:"🐯",name:"tiger face"},
    {char:"🦁",name:"lion"},{char:"🐮",name:"cow face"},
    {char:"🐷",name:"pig face"},{char:"🐸",name:"frog"},
    {char:"🐵",name:"monkey face"},{char:"🐔",name:"chicken"},
    {char:"🐧",name:"penguin"},{char:"🦆",name:"duck"},
    {char:"🦋",name:"butterfly"},{char:"🐢",name:"turtle"},
    // Food & drink
    {char:"🍎",name:"red apple"},{char:"🍊",name:"tangerine"},
    {char:"🍋",name:"lemon"},{char:"🍇",name:"grapes"},
    {char:"🍓",name:"strawberry"},{char:"🍒",name:"cherries"},
    {char:"🍑",name:"peach"},{char:"🍍",name:"pineapple"},
    {char:"🥝",name:"kiwi fruit"},{char:"🌮",name:"taco"},
    {char:"🍕",name:"pizza"},{char:"🍔",name:"hamburger"},
    {char:"🍟",name:"french fries"},{char:"🍜",name:"steaming bowl"},
    {char:"🍣",name:"sushi"},{char:"🍩",name:"doughnut"},
    {char:"🍪",name:"cookie"},{char:"🎂",name:"birthday cake"},
    {char:"☕",name:"hot beverage"},{char:"🍺",name:"beer mug"},
    // Nature
    {char:"🌸",name:"cherry blossom"},{char:"🌺",name:"hibiscus"},
    {char:"🌻",name:"sunflower"},{char:"🌹",name:"rose"},
    {char:"🌿",name:"herb"},{char:"🍃",name:"leaf fluttering in wind"},
    {char:"🍂",name:"fallen leaf"},{char:"🍁",name:"maple leaf"},
    {char:"🌊",name:"water wave"},{char:"🔥",name:"fire"},
    {char:"⚡",name:"high voltage"},{char:"❄️",name:"snowflake"},
    {char:"🌈",name:"rainbow"},{char:"☀️",name:"sun"},
    {char:"🌙",name:"crescent moon"},
    // Travel & places
    {char:"🚗",name:"automobile"},{char:"✈️",name:"airplane"},
    {char:"🚀",name:"rocket"},{char:"🛸",name:"flying saucer"},
    {char:"🚂",name:"locomotive"},{char:"⛵",name:"sailboat"},
    {char:"🏠",name:"house"},{char:"🏖️",name:"beach with umbrella"},
    {char:"🗺️",name:"world map"},{char:"🌍",name:"globe europe africa"},
    // Objects
    {char:"💻",name:"laptop"},{char:"📱",name:"mobile phone"},
    {char:"⌨️",name:"keyboard"},{char:"🖥️",name:"desktop computer"},
    {char:"📷",name:"camera"},{char:"🎤",name:"microphone"},
    {char:"📚",name:"books"},{char:"✏️",name:"pencil"},
    {char:"📝",name:"memo"},{char:"🔑",name:"key"},
    {char:"🔒",name:"locked"},{char:"💡",name:"light bulb"},
    {char:"🔧",name:"wrench"},{char:"🎮",name:"video game"},
    {char:"🎵",name:"musical note"},{char:"🎶",name:"musical notes"},
    // Symbols & misc
    {char:"✅",name:"check mark button"},{char:"❌",name:"cross mark"},
    {char:"⭐",name:"star"},{char:"💫",name:"dizzy"},
    {char:"✨",name:"sparkles"},{char:"💥",name:"collision"},
    {char:"💯",name:"hundred points"},{char:"🎉",name:"party popper"},
    {char:"🎊",name:"confetti ball"},{char:"🏆",name:"trophy"},
    {char:"🎯",name:"bullseye"},{char:"🚩",name:"triangular flag"},
    {char:"⚠️",name:"warning"},{char:"🔔",name:"bell"},
    {char:"📢",name:"loudspeaker"},{char:"💬",name:"speech bubble"},
]
